### PR TITLE
Enhance email bodies

### PR DESCRIPTION
**Pull request by joaodiaslobo**
This pull request adds some new UI elements to the bodies of emails that are sent to customers when their order status is updated. The most notable addition is a table that displays the products that were bought in the order, along with a description matching the specific status update.

In addition, the HTML code follows common best practices to ensure that the emails will display correctly on _most_ email clients.

_PREVIEW:_
image

### CODE REVIEW

**Review by MarioRodrigues10 — CHANGES_REQUESTED** [review]
Could you please add the QRCode related to the order to the email body.

**Comment by joaodiaslobo** [comment]
> Could you please add the QRCode related to the order to the email body.

Done!

_PREVIEW:_
image

**Review by MarioRodrigues10 — CHANGES_REQUESTED** [review]
It looks everything alright, but could you please remove the text body that it is being sent on email when an order status is updated.
You could find that out in this folder ```lib/store_web/templates/email```

**Review by MarioRodrigues10 — APPROVED** [review]
Good job !! :+1:

**Pull request merged**
